//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupperum_Dedikeret_Klient.ServiceRefGRum {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceRefGRum.IGrumService")]
    public interface IGrumService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrumService/SayHello", ReplyAction="http://tempuri.org/IGrumService/SayHelloResponse")]
        string SayHello();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrumService/SayHello", ReplyAction="http://tempuri.org/IGrumService/SayHelloResponse")]
        System.Threading.Tasks.Task<string> SayHelloAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGrumServiceChannel : Grupperum_Dedikeret_Klient.ServiceRefGRum.IGrumService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrumServiceClient : System.ServiceModel.ClientBase<Grupperum_Dedikeret_Klient.ServiceRefGRum.IGrumService>, Grupperum_Dedikeret_Klient.ServiceRefGRum.IGrumService {
        
        public GrumServiceClient() {
        }
        
        public GrumServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GrumServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrumServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GrumServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello() {
            return base.Channel.SayHello();
        }
        
        public System.Threading.Tasks.Task<string> SayHelloAsync() {
            return base.Channel.SayHelloAsync();
        }
    }
}
